Added DDS238 ZN/S energy meter plugin
ycahome/pp-manager pull request #49
Opened 2024-01-29 16:56 UTC by CreasolTech

2024-01-29 19:06 UTC, ycahome approved these changes

2024-01-29 19:07 UTC, ycahome requested changes
please increase versions

2024-02-05 12:11 UTC, CreasolTech commented
Version increased to 1.5.40

2024-02-06 06:41 UTC, ycahome approved these changes

2024-02-06 06:41 UTC, merged